### ISSUE TITLE
Unclear variable names

### ISSUE THREAD

**Issue by sdleffler** [nickup9/n-pong#4]
```playerOne``` - actually a score variable. Recommend renaming to ```playerOneScore```.
```playerTwo``` - ditto.
```paddleOneX```/```paddleOneY```/```paddleTwoX```/```paddleTwoY```/```puckX```/```puckY``` - just looking at these variable names suggests that they are real numbers, not lists of coordinates. Usual convention in Lua for storing lists of coordinates is to store lists of coordinate pairs, not individual lists of components. For example, a square stored like this would look like ```{{0, 0}, {0, 1}, {1, 1}, {1, 0}}``` - note how each individual point is represented as one element of the list. Of course, this isn't how Love2D accepts points in its draw functions - if you're dead set on storing these things as lists of vertices which can be passed into Love's draw functions, then you'll want to store them as Love expects them. Anything else is just inconvenient.
```winCheck``` - name suggests a boolean value (checking for winner.) Not actually a boolean value, but instead an enum value (0, 1, or 2.) Suggest renaming to ```winner``` and assigning string values instead of integer values - maybe ```"none"```, ```"player1"```, and ```"player2"```, or creating integer constants to represent the winners and make code using this variable more clear.

**Comment by nickup9** [comment]
Names of various variables and returnDefaults() made clearer.
